uploads = []

[[generated]]
id = "Igsoly0MmICKrSoMEQfwJ"
uri = "file://attached_assets/nezuko.png"
type = "image"
title = "nezuko kamado demon slayer"

[[generated]]
id = "xms5Suf9G5RlyYg19sVZf"
uri = "file://attached_assets/nezuko_bg.png"
type = "image"
title = "nezuko fullscreen background"

[[generated]]
id = "7hZSXt_aq84Q4IMWrSRUB"
uri = "file://attached_assets/nezuko_love.png"
type = "image"
title = "nezuko love heart cute"

[[generated]]
id = "kCn2rSaw45rbmEYBpgLzh"
uri = "file://attached_assets/nezuko_pubg_banner.png"
type = "image"
title = "nezuko pubg shooting banner"

[[generated]]
id = "V1hzDMPeNX5XYtBo4CMOS"
uri = "file://attached_assets/nezuko_tg_gifts_banner.png"
type = "image"
title = "nezuko holding teddy bear gifts banner"

[[outputs]]
id = "HvEuesN1vTAPtTV58peQ-"
uri = "file://attached_assets/nezuko.png"
type = "image"
title = "Незуко — сгенерированная картинка"

[[outputs]]
id = "0_7ba1Hhwl5Ht3KPuvwIU"
uri = "file://attached_assets/nezuko_bg.png"
type = "image"
title = "Незуко — новый фон"

[[outputs]]
id = "FQESfPA9auY3IGy73ux8n"
uri = "file://attached_assets/nezuko_love.png"
type = "image"
title = "Незуко любит тебя ❤️"
